-- 创建 users 表
CREATE TABLE IF NOT EXISTS User (
  id INTEGER PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(128) NOT NULL
);

-- 创建 projects 表
CREATE TABLE IF NOT EXISTS Project (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  name VARCHAR(64) NOT NULL,
  year INTERVAL NOT NULL DEFAULT '00:00:00',
  month INTERVAL NOT NULL DEFAULT '00:00:00',
  week INTERVAL NOT NULL DEFAULT '00:00:00',
  day INTERVAL NOT NULL DEFAULT '00:00:00',
  all INTERVAL NOT NULL DEFAULT '00:00:00',
  FOREIGN KEY (User_id) REFERENCES Users (id)
);

-- 创建 records 表
CREATE TABLE IF NOT EXISTS Record (
  id INTEGER PRIMARY KEY,
  project_id INTEGER NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  duration INTERVAL NOT NULL,
  FOREIGN KEY (Project_id) REFERENCES Project (id)
);



